# select profile https://stackoverflow.com/questions/62999149/how-can-i-use-environment-specific-variables-in-micronaut
micronaut:
  application:
    name: demo

app:
  mongoDbName: okno
  mongoDbTelemetryCollection: telemetry
  mongoDbReportCollection: report