# select profile https://stackoverflow.com/questions/65795595/how-to-choose-quarkus-profile-when-running-app-under-idea
# profile properties can be set by prefixing property: https://antoniogoncalves.org/2019/11/07/configuring-a-quarkus-application-with-profiles/
greeting:
  message: "hello"

"%dev":
  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017/test

"%prod":
  quarkus:
    mongodb:
      connection-string: <PLACEHOLDER>