# select profile https://stackoverflow.com/questions/65795595/how-to-choose-quarkus-profile-when-running-app-under-idea
greeting:
  message: "hello"

mp:
  messaging:
    incoming:
      movies-in:
        connector: smallrye-kafka
        topic: movies
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
    outgoing:
      movies-out:
        connector: smallrye-kafka
        topic: movies
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
