FROM adoptopenjdk:11.0.11_9-jre-hotspot-focal
COPY build/libs/micronaut-app-1.0-SNAPSHOT-all.jar /usr/app/micronaut-app-1.0-SNAPSHOT-all.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app/micronaut-app-1.0-SNAPSHOT-all.jar"]