FROM adoptopenjdk:11.0.11_9-jre-hotspot-focal
COPY build/libs/springboot-app-1.0-SNAPSHOT.jar /usr/app/springboot-app-1.0-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app/springboot-app-1.0-SNAPSHOT.jar"]