name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Add execute access to maven wrapper
        run: chmod 755 gradlew

      - name: Build and test
        run: ./gradlew build --info --stacktrace

      - name: Build Quarkus native
        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true

      - name: Create Quarkus jvm image
        run: docker build -f quarkus-app/src/main/docker/Dockerfile.jvm -t lukaszjozwiak/quarkus-app:jvm quarkus-app

      - name: Create Quarkus native image
        run: docker build -f quarkus-app/src/main/docker/Dockerfile.native -t lukaszjozwiak/quarkus-app:native quarkus-app

      - name: Create Micronaut jvm image
        run: docker build -f micronaut-app/src/main/docker/Dockerfile.jvm -t lukaszjozwiak/micronaut-app:jvm micronaut-app

      - name: Create Micronaut native image
        run: ./gradlew micronaut-app:dockerBuildNative

      - name: Rename Micronaut native image
        run: docker image tag micronaut-app:latest lukaszjozwiak/micronaut-app:native

      - name: Set up QEMU
        if: github.ref == 'refs/heads/master'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/master'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Quarkus jvm image
        if: github.ref == 'refs/heads/master'
        run:  docker push lukaszjozwiak/quarkus-app:jvm

      - name: Push Quarkus native image
        if: github.ref == 'refs/heads/master'
        run:  docker push lukaszjozwiak/quarkus-app:native

      - name: Push Micronaut jvm image
        if: github.ref == 'refs/heads/master'
        run:  docker push lukaszjozwiak/micronaut-app:jvm

      - name: Push Micronaut native image
        if: github.ref == 'refs/heads/master'
        run:  docker push lukaszjozwiak/micronaut-app:native